#!/usr/bin/perl

=head1 NAME

	perlanalyst -- perform static analysis on Perl documents

=head1 SYNOPSIS

perlanalyst

perlanalyst I<directory>

perlanalyst I<directory> I<plugin list>

=head1 DESCRIPTION

This program is the main driver for the L<Perl::Analysis::Static>
siute for modules. It performs a number of static analyses on
Perl documents.

=head1 OPTIONS

=over

=item B<--file>|B<-f> I<file>

Analyze only this file.

=item B<--dbfile>|B<-db> I<file>

The sqlite database is stored in this file.

=item B<--debug>

Print debugging output.

=item B<--directory>|B<-d> I<directory>

Add this directory to the list of files.

=item B<--help>

Print usage information.

=item B<--plugin>|B<-p> I<plugin name>

If specified, only this plugin is run.

=item B<--verbose>

Be verbose when analyzing.

=back

=cut

use strict;
use warnings;

use Getopt::Long;

use Perl::Analysis::Static::Log qw(set_debug debug);
use Perl::Analysis::Static::DB qw(connect_to_database);
use Perl::Analysis::Static::Plugins qw(load_plugins);
use Perl::Analysis::Static::File qw(add_directory);
use Perl::Analysis::Static::Analysis qw(analyze);
use Perl::Analysis::Static::Configuration qw(read_configuration);
use Perl::Analysis::Static::PluginList qw(command_list_plugins);
use Perl::Analysis::Static::PluginRanForFile qw(command_list_plugin_runs);

our %parameters;

# set defaults
$parameters{configuration}="$ENV{HOME}/perlanalyst.cfg";
$parameters{dbfile}="$ENV{HOME}/perlanalyst.sqlite";
$parameters{help}=0;
$parameters{debug}=0;

# read file name
#GetOptions(\%parameters, 'configuration=s');

read_configuration($parameters{configuration});

# read other command line arguments
read_arguments(\%parameters);

# print usage if user calls for help
if ($parameters{help}) {
	usage();
	exit;
}

# do we want debugging output?
set_debug() if $parameters{debug};

connect_to_database($parameters{dbfile});

# list plugins if asked to
if ($parameters{'list-plugins'}) {
	command_list_plugins();
	exit;
}

# list plugin runs if asked to
if ($parameters{'list-plugin-runs'}) {
	command_list_plugin_runs();
	exit;
}

load_plugins();

create_tables();

# add directory of Perl documents if provided
if ($ARGV[0]) {
	add_directory($ARGV[0]);
}


# analyze all files in the database
analyze();

sub read_arguments {
	my ($parameters)=@_;
	
	unless(GetOptions($parameters, 'file=s', 'directory=s',
	'plugin=s', 'dbfile=s', 'help!', 'debug!', 'verbose!',
	'list-plugins!', 'list-plugin-runs!')) {
		die "Unable to read arguments";
	}

}

sub usage {
	print <<EOT
perlanalyst

file
dbfile
directory
help
plugin

EOT
}

=head1 AUTHOR

Gregor Goldbach E<lt>ggoldbach AT cpan DOT org<gt>

=head1 SEE ALSO

L<Perl::Analysis::Static>, L<PPI>

=head1 COPYRIGHT

Copyright 2008 Gregor Goldbach. All rights reserved.

This program is free software; you can redistribute
it and/or modify it under the same terms as Perl itself.

The full text of the license can be found in the
LICENSE file included with this module.

=cut
